# Generated by Django 6.0.6 on 2026-06-09 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KVKKConsentLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "consent_type",
                    models.CharField(
                        choices=[
                            ("AYDINLATMA_METNI", "Aydınlatma Metni"),
                            ("ACIK_RIZA_SAGLIK", "Açık Rıza — Sağlık Verileri"),
                            ("COOKIE_ESSENTIAL", "Zorunlu Çerezler"),
                            ("COOKIE_ANALYTICS", "Analitik Çerezler"),
                            ("COOKIE_MARKETING", "Pazarlama Çerezleri"),
                        ],
                        max_length=32,
                    ),
                ),
                ("is_accepted", models.BooleanField()),
                ("kvkk_version", models.CharField(default="v1.0", max_length=16)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="kvkk_consents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "KVKK Consent Log",
                "verbose_name_plural": "KVKK Consent Logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "consent_type"],
                        name="kvkk_kvkkco_user_id_f43315_idx",
                    ),
                    models.Index(
                        fields=["consent_type", "timestamp"],
                        name="kvkk_kvkkco_consent_5a107e_idx",
                    ),
                ],
            },
        ),
    ]
