[phases.build]
cmds = [
  "pip install -r requirements.txt",
  "python manage.py collectstatic --noinput"
]

[phases.deploy]
cmd = "gunicorn fizyotech.wsgi --bind 0.0.0.0:$PORT --workers 2 --timeout 120"
