# Generated by Django 6.0.6 on 2026-06-09 20:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                (
                    "instructions",
                    models.TextField(help_text="Adım adım hareket talimatları"),
                ),
                (
                    "target_region",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("neck", "Boyun"),
                            ("shoulder_left", "Sol Omuz"),
                            ("shoulder_right", "Sağ Omuz"),
                            ("upper_back", "Üst Sırt"),
                            ("lower_back", "Bel"),
                            ("hip_left", "Sol Kalça"),
                            ("hip_right", "Sağ Kalça"),
                            ("knee_left", "Sol Diz"),
                            ("knee_right", "Sağ Diz"),
                        ],
                        max_length=32,
                    ),
                ),
                ("duration_minutes", models.PositiveSmallIntegerField(default=10)),
                ("sets", models.PositiveSmallIntegerField(default=3)),
                ("reps", models.PositiveSmallIntegerField(default=10)),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Kolay"),
                            ("medium", "Orta"),
                            ("hard", "Zor"),
                        ],
                        default="easy",
                        max_length=16,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="ExerciseAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "therapist_note",
                    models.TextField(
                        blank=True, help_text="Terapistin ev programı notu"
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Her gün"),
                            ("every_other_day", "Gün aşırı"),
                            ("weekly", "Haftada 3"),
                            ("as_needed", "İhtiyaç halinde"),
                        ],
                        default="daily",
                        max_length=24,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("start_date", models.DateField(auto_now_add=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_exercises",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="wellness.exercise",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercise_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExerciseCompletion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pain_before",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("pain_after", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("note", models.CharField(blank=True, max_length=255)),
                ("completed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="completions",
                        to="wellness.exerciseassignment",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercise_completions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-completed_at"],
            },
        ),
        migrations.CreateModel(
            name="RegionPainLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("neck", "Boyun"),
                            ("shoulder_left", "Sol Omuz"),
                            ("shoulder_right", "Sağ Omuz"),
                            ("upper_back", "Üst Sırt"),
                            ("lower_back", "Bel"),
                            ("hip_left", "Sol Kalça"),
                            ("hip_right", "Sağ Kalça"),
                            ("knee_left", "Sol Diz"),
                            ("knee_right", "Sağ Diz"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "pain_level",
                    models.PositiveSmallIntegerField(
                        help_text="0 = ağrı yok, 10 = çok şiddetli"
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=255)),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pain_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-recorded_at"],
                "indexes": [
                    models.Index(
                        fields=["patient", "region", "-recorded_at"],
                        name="wellness_re_patient_67e822_idx",
                    )
                ],
            },
        ),
    ]
