# Generated by Django 6.0.6 on 2026-06-12 19:22

import wellness.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wellness", "0002_seed_exercises"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=wellness.models.exercise_image_path
            ),
        ),
    ]
