# Generated by Django 6.0.6 on 2026-06-29 13:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wellness", "0004_dailysteplog_dailywaterlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("water", "Su Hatırlatması"),
                            ("steps", "Adım Hatırlatması"),
                            ("exercise", "Egzersiz Hatırlatması"),
                            ("custom", "Özel Mesaj"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("message", models.TextField()),
                ("send_time", models.TimeField()),
                (
                    "days_of_week",
                    models.JSONField(default=list, help_text="[0-6], 0=Pzt"),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                ("last_triggered_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Bildirim Zamanlaması",
                "verbose_name_plural": "Bildirim Zamanlamaları",
                "ordering": ["send_time"],
            },
        ),
    ]
