# Generated by Django 6.0.6 on 2026-06-29 13:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wellness", "0005_notificationschedule"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notificationschedule",
            options={
                "ordering": ["notification_type"],
                "verbose_name": "Bildirim Zamanlaması",
                "verbose_name_plural": "Bildirim Zamanlamaları",
            },
        ),
        migrations.RemoveField(
            model_name="notificationschedule",
            name="last_triggered_date",
        ),
        migrations.RemoveField(
            model_name="notificationschedule",
            name="send_time",
        ),
        migrations.AddField(
            model_name="notificationschedule",
            name="last_triggered_times",
            field=models.JSONField(
                default=dict,
                help_text='{"YYYY-MM-DD:HH:MM": true} çift gönderim engeli',
            ),
        ),
        migrations.AddField(
            model_name="notificationschedule",
            name="send_times",
            field=models.JSONField(
                default=list, help_text='["HH:MM", ...] formatında saat listesi'
            ),
        ),
    ]
