# Generated by Django 6.0.6 on 2026-07-29 16:28

import wellness.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wellness", "0006_alter_notificationschedule_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="video",
            field=models.FileField(
                blank=True, null=True, upload_to=wellness.models.exercise_video_path
            ),
        ),
    ]
