# Generated by Django 6.0.6 on 2026-08-03 20:05

import django.db.models.deletion
import wellness.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wellness", "0009_exercise_program_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MealLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "meal_type",
                    models.CharField(
                        choices=[
                            ("breakfast", "Kahvaltı"),
                            ("lunch", "Öğle"),
                            ("dinner", "Akşam"),
                            ("snack", "Ara Öğün"),
                        ],
                        max_length=16,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to=wellness.models.meal_photo_path
                    ),
                ),
                ("logged_at", models.DateTimeField()),
                ("admin_note", models.TextField(blank=True)),
                ("admin_note_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "admin_note_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="meal_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meal_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-logged_at"],
            },
        ),
        migrations.CreateModel(
            name="ProgramExerciseLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cycle",
                    models.PositiveSmallIntegerField(
                        default=1, help_text="Hafta/döngü numarası"
                    ),
                ),
                ("completed_at", models.DateTimeField(auto_now_add=True)),
                ("note", models.CharField(blank=True, max_length=500)),
                (
                    "difficulty_felt",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Kullanıcının hissettiği zorluk (1-5)",
                        null=True,
                    ),
                ),
                (
                    "program_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="wellness.exerciseprogramitem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="program_exercise_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-completed_at"],
            },
        ),
    ]
