# Generated by Django 6.0.6 on 2026-08-03 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wellness", "0011_user_notification_schedule"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgramMealEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "meal_type",
                    models.CharField(
                        choices=[
                            ("breakfast", "Kahvaltı"),
                            ("lunch", "Öğle"),
                            ("dinner", "Akşam"),
                            ("snack", "Ara Öğün"),
                        ],
                        max_length=16,
                    ),
                ),
                ("description", models.TextField(help_text="Öğün içeriği / tarifler")),
                (
                    "calories",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="Tahmini kalori (kcal)", null=True
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "day",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meal_entries",
                        to="wellness.exerciseprogramday",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "meal_type"],
            },
        ),
    ]
