# Generated by Django 6.0.6 on 2026-08-03 21:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0031_site_section_programs"),
        ("wellness", "0012_program_meal_entry"),
    ]

    operations = [
        migrations.AddField(
            model_name="programmealentry",
            name="diet_items",
            field=models.ManyToManyField(
                blank=True,
                help_text="Kütüphaneden seçilen besinler",
                related_name="program_meal_entries",
                to="accounts.dietitem",
            ),
        ),
        migrations.AlterField(
            model_name="programmealentry",
            name="description",
            field=models.TextField(blank=True, help_text="Ek notlar / serbest metin"),
        ),
    ]
