# Generated by Django 6.0.6 on 2026-08-03 21:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wellness", "0013_program_meal_entry_diet_items"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="category_type",
            field=models.CharField(
                choices=[
                    ("exercise", "Egzersiz"),
                    ("diet", "Diyet Programı"),
                    ("food", "Besin"),
                ],
                max_length=16,
            ),
        ),
    ]
