# Generated by Django 6.0.6 on 2026-08-03 21:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wellness", "0014_add_food_category_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="programmealentry",
            options={"ordering": ["notification_time", "sort_order", "meal_type"]},
        ),
        migrations.AddField(
            model_name="programmealentry",
            name="notification_time",
            field=models.TimeField(
                blank=True, help_text="Bildirim saati (HH:MM)", null=True
            ),
        ),
    ]
