# Generated by Django 6.0.6 on 2026-08-03 21:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wellness", "0015_meal_entry_notification_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="programmealentry",
            name="meal_type",
            field=models.CharField(
                choices=[
                    ("sabah", "Kahvaltı"),
                    ("ara1", "Ara Öğün 1"),
                    ("ogle", "Öğle"),
                    ("ara2", "Ara Öğün 2"),
                    ("aksam", "Akşam"),
                    ("gece", "Gece"),
                ],
                max_length=16,
            ),
        ),
    ]
