# Generated by Django 6.0.6 on 2026-08-03 22:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wellness", "0016_program_meal_entry_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="productpackage",
            name="session_type",
            field=models.CharField(
                choices=[("group", "Grup Dersi"), ("private", "Özel Ders")],
                default="group",
                max_length=16,
            ),
        ),
    ]
