# Generated by Django 6.0.6 on 2026-06-09 20:03

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientProgressPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to=accounts.models.patient_photo_path),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("posture_front", "Önden (Postür)"),
                            ("posture_side", "Yandan (Postür)"),
                            ("posture_back", "Arkadan (Postür)"),
                            ("exercise", "Egzersiz"),
                            ("general", "Genel"),
                            ("other", "Diğer"),
                        ],
                        default="posture_front",
                        max_length=32,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=120)),
                ("note", models.TextField(blank=True)),
                ("taken_at", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_photos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_patient_photos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Patient Progress Photo",
                "verbose_name_plural": "Patient Progress Photos",
                "ordering": ["-taken_at", "-created_at"],
            },
        ),
    ]
