# Generated by Django 6.0.6 on 2026-06-12 11:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_sessionpackage"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=40)),
                ("subject", models.CharField(blank=True, max_length=160)),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "İletişim Mesajı",
                "verbose_name_plural": "İletişim Mesajları",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("clinic_name", models.CharField(default="FizyoTech", max_length=120)),
                ("address", models.TextField(blank=True)),
                ("phone", models.CharField(blank=True, max_length=40)),
                ("whatsapp", models.CharField(blank=True, max_length=40)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "working_hours",
                    models.TextField(
                        blank=True, help_text="Örn. Pazartesi–Cuma 09:00–18:00"
                    ),
                ),
                (
                    "map_embed_url",
                    models.URLField(
                        blank=True,
                        help_text="Google Haritalar 'embed' iframe src bağlantısı",
                        max_length=600,
                    ),
                ),
                ("instagram_url", models.URLField(blank=True)),
                ("facebook_url", models.URLField(blank=True)),
                ("x_url", models.URLField(blank=True, verbose_name="X (Twitter) URL")),
                ("youtube_url", models.URLField(blank=True)),
                ("linkedin_url", models.URLField(blank=True)),
                (
                    "google_analytics_id",
                    models.CharField(
                        blank=True, help_text="Örn. G-XXXXXXXXXX", max_length=40
                    ),
                ),
                (
                    "google_search_console_verification",
                    models.CharField(
                        blank=True,
                        help_text="Search Console 'HTML etiketi' doğrulama içeriği (content değeri)",
                        max_length=120,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Site Ayarları",
                "verbose_name_plural": "Site Ayarları",
            },
        ),
    ]
