# Generated by Django 6.0.6 on 2026-06-12 12:18

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_packageplan_sessionpackage_is_paid_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PostureAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "view",
                    models.CharField(
                        choices=[
                            ("front", "Önden"),
                            ("side", "Yandan"),
                            ("back", "Arkadan"),
                        ],
                        default="front",
                        max_length=10,
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to=accounts.models.posture_image_path),
                ),
                ("metrics", models.JSONField(blank=True, default=dict)),
                ("summary", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_posture_assessments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posture_assessments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Postür Analizi",
                "verbose_name_plural": "Postür Analizleri",
                "ordering": ["-created_at"],
            },
        ),
    ]
