# Generated by Django 6.0.6 on 2026-06-27 19:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0011_bodymeasurement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bodymeasurement",
            name="alt_karin",
            field=models.FloatField(blank=True, help_text="Alt karın (cm)", null=True),
        ),
        migrations.AlterField(
            model_name="bodymeasurement",
            name="basen",
            field=models.FloatField(blank=True, help_text="Basen (cm)", null=True),
        ),
        migrations.AlterField(
            model_name="bodymeasurement",
            name="bel",
            field=models.FloatField(blank=True, help_text="Bel (cm)", null=True),
        ),
        migrations.AlterField(
            model_name="bodymeasurement",
            name="gobek",
            field=models.FloatField(blank=True, help_text="Göbek (cm)", null=True),
        ),
        migrations.AlterField(
            model_name="bodymeasurement",
            name="gogus",
            field=models.FloatField(blank=True, help_text="Göğüs (cm)", null=True),
        ),
        migrations.AlterField(
            model_name="bodymeasurement",
            name="kalca",
            field=models.FloatField(blank=True, help_text="Kalça (cm)", null=True),
        ),
        migrations.AlterField(
            model_name="bodymeasurement",
            name="label",
            field=models.CharField(
                blank=True,
                help_text="Ölçüm etiketi, örn. 'Başlangıç', 'Ara Ölçüm'",
                max_length=80,
            ),
        ),
        migrations.AlterField(
            model_name="bodymeasurement",
            name="omuz",
            field=models.FloatField(blank=True, help_text="Omuz (cm)", null=True),
        ),
        migrations.AlterField(
            model_name="bodymeasurement",
            name="sag_bacak",
            field=models.FloatField(blank=True, help_text="Sağ bacak (cm)", null=True),
        ),
        migrations.AlterField(
            model_name="bodymeasurement",
            name="sag_kol",
            field=models.FloatField(blank=True, help_text="Sağ kol (cm)", null=True),
        ),
        migrations.AlterField(
            model_name="bodymeasurement",
            name="sol_bacak",
            field=models.FloatField(blank=True, help_text="Sol bacak (cm)", null=True),
        ),
        migrations.AlterField(
            model_name="bodymeasurement",
            name="sol_kol",
            field=models.FloatField(blank=True, help_text="Sol kol (cm)", null=True),
        ),
        migrations.AlterField(
            model_name="bodymeasurement",
            name="weight",
            field=models.FloatField(blank=True, help_text="Kilo (kg)", null=True),
        ),
        migrations.AlterField(
            model_name="bodymeasurement",
            name="yag_orani",
            field=models.FloatField(blank=True, help_text="Yağ oranı (%)", null=True),
        ),
    ]
