# Generated by Django 6.0.6 on 2026-06-28 18:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0013_faq"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="registration_enabled",
            field=models.BooleanField(
                default=True, help_text="Anasayfadaki kayıt ol bölümünü göster/gizle"
            ),
        ),
    ]
