# Generated by Django 6.0.6 on 2026-06-28 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0014_sitesettings_registration_enabled"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DietItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("calories", models.PositiveIntegerField(help_text="kcal")),
                (
                    "protein",
                    models.DecimalField(
                        decimal_places=1, default=0, help_text="gram", max_digits=6
                    ),
                ),
                (
                    "carbs",
                    models.DecimalField(
                        decimal_places=1, default=0, help_text="gram", max_digits=6
                    ),
                ),
                (
                    "fat",
                    models.DecimalField(
                        decimal_places=1, default=0, help_text="gram", max_digits=6
                    ),
                ),
                (
                    "portion",
                    models.CharField(
                        blank=True, help_text="örn: 1 kase, 200 g", max_length=80
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Besin",
                "verbose_name_plural": "Besinler",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DietPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("date", models.DateField(help_text="Planın uygulanacağı tarih")),
                (
                    "meal_type",
                    models.CharField(
                        choices=[
                            ("sabah", "Kahvaltı"),
                            ("ara1", "Ara Öğün 1"),
                            ("ogle", "Öğle"),
                            ("ara2", "Ara Öğün 2"),
                            ("aksam", "Akşam"),
                            ("gece", "Gece"),
                        ],
                        default="ogle",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_diet_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diet_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Diyet Planı",
                "verbose_name_plural": "Diyet Planları",
                "ordering": ["date", "meal_type"],
            },
        ),
        migrations.CreateModel(
            name="DietPlanItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=1,
                        help_text="Porsiyon çarpanı",
                        max_digits=5,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=200)),
                (
                    "diet_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.dietitem",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plan_items",
                        to="accounts.dietplan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plan Besini",
                "verbose_name_plural": "Plan Besinleri",
            },
        ),
        migrations.AddField(
            model_name="dietplan",
            name="items",
            field=models.ManyToManyField(
                blank=True, through="accounts.DietPlanItem", to="accounts.dietitem"
            ),
        ),
    ]
