# Generated by Django 6.0.6 on 2026-06-28 19:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0016_attendance_record"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="expert_badges",
            field=models.TextField(
                blank=True,
                default="Ortopedik Rehabilitasyon,Spor Yaralanmaları,3D Postür Analizi,Manuel Terapi",
                help_text="Virgülle ayrılmış uzmanlık etiketleri",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="expert_bio",
            field=models.TextField(
                blank=True,
                default="15 yıllık deneyimiyle dijital fizyoterapi alanında öncü. Kişiselleştirilmiş 3D tedavi planları ve veri odaklı rehabilitasyon yaklaşımıyla 2.000+ hastaya hizmet vermiştir.",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="expert_name",
            field=models.CharField(
                blank=True, default="Dr. Ayşe Yılmaz", max_length=120
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="expert_patient_count",
            field=models.CharField(blank=True, default="2.000+", max_length=20),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="expert_rating",
            field=models.CharField(blank=True, default="4.9", max_length=10),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="expert_title",
            field=models.CharField(
                blank=True,
                default="Fizyoterapist & Ortopedik Rehabilitasyon Uzmanı",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="expert_visible",
            field=models.BooleanField(
                default=True,
                help_text="Anasayfadaki uzman profil bölümünü göster/gizle",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="expert_years",
            field=models.PositiveSmallIntegerField(default=15, help_text="Yıl deneyim"),
        ),
    ]
