# Generated by Django 6.0.6 on 2026-06-28 19:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0017_expert_profile_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "treatment",
                    models.CharField(
                        blank=True,
                        help_text="Tedavi türü (örn. Bel Ağrısı)",
                        max_length=100,
                    ),
                ),
                ("text", models.TextField()),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "1 Yıldız"),
                            (2, "2 Yıldız"),
                            (3, "3 Yıldız"),
                            (4, "4 Yıldız"),
                            (5, "5 Yıldız"),
                        ],
                        default=5,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Hasta Yorumu",
                "verbose_name_plural": "Hasta Yorumları",
                "ordering": ["sort_order", "created_at"],
            },
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="section_about",
            field=models.BooleanField(default=True, verbose_name="Hakkımızda"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="section_cta",
            field=models.BooleanField(default=True, verbose_name="CTA Banner"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="section_digital_twin",
            field=models.BooleanField(default=True, verbose_name="Dijital İkiz"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="section_faq",
            field=models.BooleanField(default=True, verbose_name="SSS"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="section_how_it_works",
            field=models.BooleanField(default=True, verbose_name="Nasıl Çalışır"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="section_marquee",
            field=models.BooleanField(default=True, verbose_name="Marka Marquee"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="section_packages",
            field=models.BooleanField(default=True, verbose_name="Paketler"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="section_services",
            field=models.BooleanField(default=True, verbose_name="Hizmetler"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="section_stats",
            field=models.BooleanField(default=True, verbose_name="İstatistik Şeridi"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="section_testimonials",
            field=models.BooleanField(default=True, verbose_name="Hasta Yorumları"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="section_treatments",
            field=models.BooleanField(default=True, verbose_name="Tedavi Alanları"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="section_why_us",
            field=models.BooleanField(default=True, verbose_name="Neden JFS"),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="registration_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
