# Generated by Django 6.0.6 on 2026-06-28 19:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0018_testimonial_and_section_visibility"),
    ]

    operations = [
        migrations.CreateModel(
            name="LandingService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="🎯", help_text="Emoji ikon", max_length=10
                    ),
                ),
                (
                    "tag",
                    models.CharField(
                        blank=True,
                        help_text="Kart etiketi (örn. Bireysel)",
                        max_length=40,
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("description", models.TextField()),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Hizmet",
                "verbose_name_plural": "Hizmetler",
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="LandingTreatment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("description", models.TextField()),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Tedavi Alanı",
                "verbose_name_plural": "Tedavi Alanları",
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="LandingWhyUsItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="✅", help_text="Emoji ikon", max_length=10
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("description", models.TextField()),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Neden JFS Maddesi",
                "verbose_name_plural": "Neden JFS Maddeleri",
                "ordering": ["sort_order"],
            },
        ),
    ]
