# Generated by Django 6.0.6 on 2026-06-29 12:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0020_onboarding"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientprofile",
            name="target_body_fat",
            field=models.FloatField(
                blank=True, help_text="Hedef yağ oranı (%)", null=True
            ),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="target_chest",
            field=models.FloatField(
                blank=True, help_text="Hedef göğüs (cm)", null=True
            ),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="target_hip",
            field=models.FloatField(
                blank=True, help_text="Hedef kalça (cm)", null=True
            ),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="target_waist",
            field=models.FloatField(blank=True, help_text="Hedef bel (cm)", null=True),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="target_weight",
            field=models.FloatField(blank=True, help_text="Hedef kilo (kg)", null=True),
        ),
    ]
