# Generated by Django 6.0.6 on 2026-06-29 15:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0021_patientprofile_target_body_fat_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientprofile",
            name="daily_water_goal_ml",
            field=models.PositiveIntegerField(
                default=2000, help_text="Günlük su hedefi (ml)"
            ),
        ),
    ]
