# Generated by Django 6.0.6 on 2026-07-04 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0022_add_daily_water_goal"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancerecord",
            name="session_package",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attendance_records",
                to="accounts.sessionpackage",
            ),
        ),
    ]
