# Generated by Django 6.0.6 on 2026-07-11 21:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0023_attendance_record_package_fk"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DietDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day_number", models.PositiveSmallIntegerField()),
                (
                    "label",
                    models.CharField(
                        blank=True, help_text="örn: Pazartesi, Gün 1", max_length=50
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "verbose_name": "Diyet Günü",
                "verbose_name_plural": "Diyet Günleri",
                "ordering": ["day_number"],
            },
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="clinic_name",
            field=models.CharField(default="JFS Method", max_length=120),
        ),
        migrations.CreateModel(
            name="DietMeal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "meal_type",
                    models.CharField(
                        choices=[
                            ("sabah", "Kahvaltı"),
                            ("ara1", "Ara Öğün 1"),
                            ("ogle", "Öğle"),
                            ("ara2", "Ara Öğün 2"),
                            ("aksam", "Akşam"),
                            ("gece", "Gece"),
                            ("serbest", "Serbest Öğün"),
                        ],
                        default="ogle",
                        max_length=10,
                    ),
                ),
                (
                    "meal_time",
                    models.CharField(blank=True, help_text="örn: 12:00", max_length=10),
                ),
                ("description", models.CharField(blank=True, max_length=300)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "day",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meals",
                        to="accounts.dietday",
                    ),
                ),
            ],
            options={
                "verbose_name": "Öğün",
                "verbose_name_plural": "Öğünler",
                "ordering": ["order", "meal_type"],
            },
        ),
        migrations.CreateModel(
            name="DietMealItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "quantity",
                    models.DecimalField(decimal_places=2, default=1, max_digits=5),
                ),
                ("calories", models.PositiveIntegerField(default=0)),
                ("note", models.CharField(blank=True, max_length=200)),
                (
                    "diet_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.dietitem",
                    ),
                ),
                (
                    "meal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="accounts.dietmeal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Öğün Besini",
                "verbose_name_plural": "Öğün Besinleri",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="DietProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "goals",
                    models.TextField(
                        blank=True, help_text="Hedefler (her satır bir madde)"
                    ),
                ),
                (
                    "feeding_notes",
                    models.CharField(
                        blank=True,
                        help_text="örn: 20.00 sonrası sadece su",
                        max_length=300,
                    ),
                ),
                ("duration_days", models.PositiveSmallIntegerField(default=7)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_diet_programs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diet_programs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Beslenme Programı",
                "verbose_name_plural": "Beslenme Programları",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="dietday",
            name="program",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="days",
                to="accounts.dietprogram",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dietday",
            unique_together={("program", "day_number")},
        ),
    ]
