# Generated by Django 6.0.6 on 2026-07-25 18:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0025_diet_program_global"),
    ]

    operations = [
        migrations.AddField(
            model_name="sessionpackage",
            name="historical_sessions",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
