# Generated by Django 6.0.6 on 2026-07-27 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0026_add_historical_sessions_to_sessionpackage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("login", "Giriş"),
                            ("login_fail", "Başarısız Giriş"),
                            ("register", "Kayıt"),
                            ("impersonate", "Kullanıcı Olarak Giriş"),
                            ("appointment_create", "Randevu Oluşturma"),
                            ("appointment_cancel", "Randevu İptal"),
                            ("appointment_status", "Randevu Durum Güncelleme"),
                            ("package_assign", "Paket Atama"),
                            ("package_delete", "Paket Silme"),
                            ("package_status", "Paket Durum Güncelleme"),
                            ("attendance_mark", "Devam İşareti"),
                            ("attendance_delete", "Devam Silme"),
                            ("patient_create", "Öğrenci Oluşturma"),
                            ("patient_delete", "Öğrenci Silme"),
                            ("password_change", "Şifre Değiştirme"),
                            ("other", "Diğer"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Başarılı"),
                            ("failure", "Başarısız"),
                            ("error", "Hata"),
                        ],
                        default="success",
                        max_length=20,
                    ),
                ),
                ("detail", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs_as_actor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs_as_target",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Sistem Logu",
                "verbose_name_plural": "Sistem Logları",
                "ordering": ["-created_at"],
            },
        ),
    ]
