# Generated by Django 6.0.6 on 2026-08-03 16:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0027_add_audit_log"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("body", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Bildirim Şablonu",
                "verbose_name_plural": "Bildirim Şablonları",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("login", "Giriş"),
                    ("login_fail", "Başarısız Giriş"),
                    ("register", "Kayıt"),
                    ("impersonate", "Kullanıcı Olarak Giriş"),
                    ("appointment_create", "Randevu Oluşturma"),
                    ("appointment_cancel", "Randevu İptal"),
                    ("appointment_status", "Randevu Durum Güncelleme"),
                    ("package_assign", "Paket Atama"),
                    ("package_delete", "Paket Silme"),
                    ("package_status", "Paket Durum Güncelleme"),
                    ("attendance_mark", "Devam İşareti"),
                    ("attendance_delete", "Devam Silme"),
                    ("patient_create", "Öğrenci Oluşturma"),
                    ("patient_delete", "Öğrenci Silme"),
                    ("password_change", "Şifre Değiştirme"),
                    ("frontend_error", "Frontend Hatası"),
                    ("other", "Diğer"),
                ],
                max_length=50,
            ),
        ),
    ]
