# Generated by Django 6.0.6 on 2026-08-03 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0028_notification_template"),
        ("wellness", "0008_category_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="dietprogram",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="diet_programs",
                to="wellness.category",
            ),
        ),
    ]
