# Generated by Django 6.0.6 on 2026-08-03 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0029_dietprogram_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="OnboardingSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.CharField(blank=True, max_length=500)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Onboarding Bölümü",
                "verbose_name_plural": "Onboarding Bölümleri",
                "ordering": ["sort_order", "created_at"],
            },
        ),
        migrations.AddField(
            model_name="onboardingquestion",
            name="section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="questions",
                to="accounts.onboardingsection",
            ),
        ),
    ]
