# Generated by Django 6.0.6 on 2026-08-03 20:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0030_onboarding_section"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="section_programs",
            field=models.BooleanField(default=True, verbose_name="Programlar"),
        ),
    ]
