# Generated by Django 6.0.6 on 2026-08-03 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0031_site_section_programs"),
        ("wellness", "0013_program_meal_entry_diet_items"),
    ]

    operations = [
        migrations.AddField(
            model_name="dietitem",
            name="category",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"category_type": "diet"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="diet_items",
                to="wellness.category",
            ),
        ),
    ]
