# Generated by Django 6.0.6 on 2026-08-03 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0032_dietitem_category"),
        ("wellness", "0017_add_product_package_session_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="sessionpackage",
            name="product_package",
            field=models.ForeignKey(
                blank=True,
                help_text="Bu paketin bağlı olduğu ürün paketi (grup/özel ders tipi buradan alınır)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="session_packages",
                to="wellness.productpackage",
            ),
        ),
        migrations.AlterField(
            model_name="dietitem",
            name="category",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"category_type": "food"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="diet_items",
                to="wellness.category",
            ),
        ),
    ]
