# Generated by Django 6.0.6 on 2026-08-03 22:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0033_add_session_package_product_package"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sessionpackage",
            name="product_package",
        ),
        migrations.AddField(
            model_name="packageplan",
            name="session_type",
            field=models.CharField(
                choices=[("group", "Grup Dersi"), ("private", "Özel Ders")],
                default="group",
                max_length=16,
            ),
        ),
    ]
