# Generated by Django 6.0.6 on 2026-08-19 20:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0035_add_admin_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="postureassessment",
            name="note",
            field=models.TextField(blank=True),
        ),
    ]
