# Generated by Django 6.0.6 on 2026-08-19 20:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0036_postureassessment_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="postureassessment",
            name="admin_note",
            field=models.TextField(blank=True),
        ),
    ]
