# Generated by Django 6.0.6 on 2026-06-09 20:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appointments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClinicHoliday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("name", models.CharField(blank=True, max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Clinic Holiday",
                "verbose_name_plural": "Clinic Holidays",
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="ClinicScheduleSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slot_duration_minutes", models.PositiveIntegerField(default=30)),
            ],
            options={
                "verbose_name": "Clinic Schedule Settings",
                "verbose_name_plural": "Clinic Schedule Settings",
            },
        ),
        migrations.CreateModel(
            name="WorkingDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Pazartesi"),
                            (1, "Salı"),
                            (2, "Çarşamba"),
                            (3, "Perşembe"),
                            (4, "Cuma"),
                            (5, "Cumartesi"),
                            (6, "Pazar"),
                        ],
                        unique=True,
                    ),
                ),
                ("is_working", models.BooleanField(default=True)),
                ("start_time", models.TimeField(default=datetime.time(9, 0))),
                ("end_time", models.TimeField(default=datetime.time(18, 0))),
            ],
            options={
                "verbose_name": "Working Day",
                "verbose_name_plural": "Working Days",
                "ordering": ["day_of_week"],
            },
        ),
    ]
