# Generated by Django 6.0.6 on 2026-06-12 10:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appointments", "0004_appointment_cancellation_reason_daycancellation"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="reminder_1h_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="appointment",
            name="reminder_24h_sent",
            field=models.BooleanField(default=False),
        ),
    ]
