# Generated by Django 6.0.6 on 2026-06-12 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_sessionpackage"),
        ("appointments", "0005_appointment_reminder_1h_sent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="package",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="appointments",
                to="accounts.sessionpackage",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("postponed", "Postponed"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("no_show", "No Show"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
