# Generated by Django 6.0.6 on 2026-06-12 11:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appointments", "0006_appointment_package_alter_appointment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="clinicschedulesettings",
            name="slot_capacity",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Aynı doktor ve saatte randevu alabilecek maksimum kişi sayısı",
            ),
        ),
    ]
