# Generated by Django 6.0.6 on 2026-07-24 18:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appointments", "0007_clinicschedulesettings_slot_capacity"),
    ]

    operations = [
        migrations.CreateModel(
            name="SlotBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("reason", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Slot Block",
                "verbose_name_plural": "Slot Blocks",
                "ordering": ["date", "start_time"],
            },
        ),
    ]
