# Generated by Django 6.0.6 on 2026-07-24 19:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appointments", "0008_slot_block"),
    ]

    operations = [
        migrations.AddField(
            model_name="clinicschedulesettings",
            name="free_cancel_hours",
            field=models.PositiveIntegerField(
                default=6,
                help_text="Randevudan kaç saat öncesine kadar cezasız iptal yapılabilir",
            ),
        ),
        migrations.AddField(
            model_name="clinicschedulesettings",
            name="late_cancel_penalty_minutes",
            field=models.PositiveIntegerField(
                default=30,
                help_text="Bu dakikadan az süre kaldığında iptal edilirse seans hakkı yanar",
            ),
        ),
    ]
