# Generated by Django 6.0.6 on 2026-07-24 19:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appointments", "0009_cancel_policy"),
    ]

    operations = [
        migrations.AddField(
            model_name="clinicschedulesettings",
            name="slot_break_minutes",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Her randevu slotundan sonra bırakılacak dinlenme süresi (dakika)",
            ),
        ),
    ]
