# Generated by Django 6.0.6 on 2026-07-24 20:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appointments", "0011_ical_uid"),
    ]

    operations = [
        migrations.AddField(
            model_name="clinicschedulesettings",
            name="reminder_1h_enabled",
            field=models.BooleanField(
                default=True,
                help_text="1 saat öncesi hatırlatma bildirimi gönderilsin mi",
            ),
        ),
        migrations.AddField(
            model_name="clinicschedulesettings",
            name="reminder_24h_enabled",
            field=models.BooleanField(
                default=True,
                help_text="24 saat öncesi hatırlatma bildirimi gönderilsin mi",
            ),
        ),
        migrations.AddField(
            model_name="clinicschedulesettings",
            name="reminder_custom_minutes",
            field=models.PositiveIntegerField(
                default=0, help_text="Ekstra hatırlatma: kaç dakika öncesi (0 = kapalı)"
            ),
        ),
    ]
