# Generated by Django 6.0.6 on 2026-07-24 20:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appointments", "0012_reminder_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="reminder_custom_sent",
            field=models.BooleanField(default=False),
        ),
    ]
