# Generated by Django 6.0.6 on 2026-08-03 22:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appointments", "0013_reminder_custom_sent"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="is_private",
            field=models.BooleanField(
                default=False, help_text="Özel ders randevusu — slotu tamamen kilitler"
            ),
        ),
    ]
